twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/themeType.html.twig']
    globals:
        form_contact: '@App\Service\FormContactService'